/*
 * Copyright 2026 Robomous
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "scena/runtime/detmath.h"

#include <cmath>
#include <limits>

// Deterministic sin/cos via Cody & Waite argument reduction followed by
// fully-parenthesized Taylor kernels on [-pi/4, pi/4]. Reference for the
// reduction technique: W. J. Cody and W. Waite, "Software Manual for the
// Elementary Functions" (Prentice-Hall, 1980). The Taylor coefficients are
// exact rationals (not a Remez fit), so this file is clean-room by
// construction and reproducible from scripts/gen_detmath_coeffs.py.
//
// Only std functions that are IEEE-exact across platforms are used here
// (std::floor, std::fabs); no libm transcendental appears. This is the single
// file the detmath guard (scripts/check_detmath.sh) exempts.

namespace scena::runtime {

namespace {

// generated by scripts/gen_detmath_coeffs.py
// Cody & Waite argument reduction: 2/pi, and pi/2 split into three
// 30-bit chunks so kd*chunk is exact for |kd| < 2^22 (|x| <= 1e6).
inline constexpr double kTwoOverPi = 0x1.45f306dc9c883p-1; // 2/pi
inline constexpr double kPi2Hi = 0x1.921fb54400000p+0;
inline constexpr double kPi2Mid = 0x1.0b4611a400000p-34;
inline constexpr double kPi2Low = 0x1.13198a2c00000p-65;

// sin: r + r^3 * horner(r^2), coeffs (-1)^j/(2j+1)! for j = 1..8.
inline constexpr double kS1 = -0x1.5555555555555p-3;  // (-1)^1/3!
inline constexpr double kS2 = 0x1.1111111111111p-7;   // (-1)^2/5!
inline constexpr double kS3 = -0x1.a01a01a01a01ap-13; // (-1)^3/7!
inline constexpr double kS4 = 0x1.71de3a556c734p-19;  // (-1)^4/9!
inline constexpr double kS5 = -0x1.ae64567f544e4p-26; // (-1)^5/11!
inline constexpr double kS6 = 0x1.6124613a86d09p-33;  // (-1)^6/13!
inline constexpr double kS7 = -0x1.ae7f3e733b81fp-41; // (-1)^7/15!
inline constexpr double kS8 = 0x1.952c77030ad4ap-49;  // (-1)^8/17!

// cos: (1 - r^2/2) + r^4 * horner(r^2), coeffs (-1)^j/(2j)! for j = 2..8.
inline constexpr double kC1 = 0x1.5555555555555p-5;   // (-1)^2/4!
inline constexpr double kC2 = -0x1.6c16c16c16c17p-10; // (-1)^3/6!
inline constexpr double kC3 = 0x1.a01a01a01a01ap-16;  // (-1)^4/8!
inline constexpr double kC4 = -0x1.27e4fb7789f5cp-22; // (-1)^5/10!
inline constexpr double kC5 = 0x1.1eed8eff8d898p-29;  // (-1)^6/12!
inline constexpr double kC6 = -0x1.93974a8c07c9dp-37; // (-1)^7/14!
inline constexpr double kC7 = 0x1.ae7f3e733b81fp-45;  // (-1)^8/16!

// atan argument reduction: pi/2, pi/6, sqrt(3) and the fold
// threshold tan(pi/12) = 2 - sqrt(3).
inline constexpr double kPi = 0x1.921fb54442d18p+1;
inline constexpr double kPiOver2 = 0x1.921fb54442d18p+0;
inline constexpr double kPiOver6 = 0x1.0c152382d7366p-1;
inline constexpr double kSqrt3 = 0x1.bb67ae8584caap+0;
inline constexpr double kTanPiOver12 = 0x1.126145e9ecd56p-2;

// atan: u + u^3 * horner(u^2), coeffs (-1)^j/(2j+1) for j = 1..15.
inline constexpr double kA1 = -0x1.5555555555555p-2;  // (-1)^1/3
inline constexpr double kA2 = 0x1.999999999999ap-3;   // (-1)^2/5
inline constexpr double kA3 = -0x1.2492492492492p-3;  // (-1)^3/7
inline constexpr double kA4 = 0x1.c71c71c71c71cp-4;   // (-1)^4/9
inline constexpr double kA5 = -0x1.745d1745d1746p-4;  // (-1)^5/11
inline constexpr double kA6 = 0x1.3b13b13b13b14p-4;   // (-1)^6/13
inline constexpr double kA7 = -0x1.1111111111111p-4;  // (-1)^7/15
inline constexpr double kA8 = 0x1.e1e1e1e1e1e1ep-5;   // (-1)^8/17
inline constexpr double kA9 = -0x1.af286bca1af28p-5;  // (-1)^9/19
inline constexpr double kA10 = 0x1.8618618618618p-5;  // (-1)^10/21
inline constexpr double kA11 = -0x1.642c8590b2164p-5; // (-1)^11/23
inline constexpr double kA12 = 0x1.47ae147ae147bp-5;  // (-1)^12/25
inline constexpr double kA13 = -0x1.2f684bda12f68p-5; // (-1)^13/27
inline constexpr double kA14 = 0x1.1a7b9611a7b96p-5;  // (-1)^14/29
inline constexpr double kA15 = -0x1.0842108421084p-5; // (-1)^15/31

// Sine on the reduced argument r in [-pi/4, pi/4], Horner in r^2.
double sin_kernel(double r) noexcept {
    const double r2 = r * r;
    const double r3 = r2 * r;
    double ps = kS8;
    ps = kS7 + r2 * ps;
    ps = kS6 + r2 * ps;
    ps = kS5 + r2 * ps;
    ps = kS4 + r2 * ps;
    ps = kS3 + r2 * ps;
    ps = kS2 + r2 * ps;
    ps = kS1 + r2 * ps;
    return r + r3 * ps;
}

// Cosine on the reduced argument r in [-pi/4, pi/4], Horner in r^2.
double cos_kernel(double r) noexcept {
    const double r2 = r * r;
    const double r4 = r2 * r2;
    double pc = kC7;
    pc = kC6 + r2 * pc;
    pc = kC5 + r2 * pc;
    pc = kC4 + r2 * pc;
    pc = kC3 + r2 * pc;
    pc = kC2 + r2 * pc;
    pc = kC1 + r2 * pc;
    return (1.0 - 0.5 * r2) + r4 * pc;
}

// Arctangent on the folded argument u in [-tan(pi/12), tan(pi/12)], Horner in
// u^2. The series converges fast enough there that the first neglected term is
// ~1e-20 relative — far below one ulp.
double atan_kernel(double u) noexcept {
    const double u2 = u * u;
    const double u3 = u2 * u;
    double p = kA15;
    p = kA14 + u2 * p;
    p = kA13 + u2 * p;
    p = kA12 + u2 * p;
    p = kA11 + u2 * p;
    p = kA10 + u2 * p;
    p = kA9 + u2 * p;
    p = kA8 + u2 * p;
    p = kA7 + u2 * p;
    p = kA6 + u2 * p;
    p = kA5 + u2 * p;
    p = kA4 + u2 * p;
    p = kA3 + u2 * p;
    p = kA2 + u2 * p;
    p = kA1 + u2 * p;
    return u + u3 * p;
}

// Arctangent of a non-negative argument, in [0, pi/2]. Two exact identities
// fold the whole range onto the kernel's interval:
//   atan(t) = pi/2 - atan(1/t)                          for t > 1
//   atan(t) = pi/6 + atan((t*sqrt3 - 1)/(t + sqrt3))    for t > tan(pi/12)
// The second is the subtraction formula with atan(1/sqrt3) = pi/6.
double atan_nonnegative(double t) noexcept {
    if (!(t <= 0x1.fffffffffffffp+1023)) {
        return kPiOver2; // an overflowed quotient: the vector is on the y axis
    }
    if (t > 1.0) {
        return kPiOver2 - atan_nonnegative(1.0 / t);
    }
    if (t > kTanPiOver12) {
        return kPiOver6 + atan_kernel((t * kSqrt3 - 1.0) / (t + kSqrt3));
    }
    return atan_kernel(t);
}

} // namespace

SinCos det_sincos(double x) noexcept {
    // Preserve signed zero: sin(+/-0) = +/-0, cos(+/-0) = 1. Returning x keeps
    // the sign bit; the == comparison treats +0.0 and -0.0 as equal.
    if (x == 0.0) {
        return {x, 1.0};
    }
    // Negated comparison so NaN (all comparisons false) and +/-inf fall out of
    // the accepted domain along with plain over-range magnitudes.
    if (!(std::fabs(x) <= kDetTrigMaxAbsInput)) {
        const double qnan = std::numeric_limits<double>::quiet_NaN();
        return {qnan, qnan};
    }

    // Cody & Waite: reduce x to r in [-pi/4, pi/4] and a quadrant index n.
    // kd is the nearest integer multiple of pi/2; subtracting the 30-bit split
    // one chunk at a time keeps each product kd*chunk exact.
    const double kd = std::floor(x * kTwoOverPi + 0.5);
    const double r = ((x - kd * kPi2Hi) - kd * kPi2Mid) - kd * kPi2Low;
    const int n = static_cast<int>(static_cast<long long>(kd) & 3);

    const double s = sin_kernel(r);
    const double c = cos_kernel(r);
    switch (n) {
    case 0:
        return {s, c};
    case 1:
        return {c, -s};
    case 2:
        return {-s, -c};
    default: // n == 3
        return {-c, s};
    }
}

double det_sin(double x) noexcept {
    // x == -0.0 short-circuits through det_sincos, which returns x, so the
    // -0.0 -> -0.0 guarantee holds without special-casing here.
    return det_sincos(x).sin;
}

double det_cos(double x) noexcept {
    return det_sincos(x).cos;
}

double det_atan2(double y, double x) noexcept {
    // NaN and +/-inf are out of domain (see the header): the runtime never
    // feeds them in, and answering would mask the defect that produced them.
    if (!(std::fabs(x) <= std::numeric_limits<double>::max()) ||
        !(std::fabs(y) <= std::numeric_limits<double>::max())) {
        return std::numeric_limits<double>::quiet_NaN();
    }
    if (x == 0.0) {
        if (y == 0.0) {
            // IEEE: atan2(+/-0, +0) = +/-0 and atan2(+/-0, -0) = +/-pi. The
            // sign bit of the zero x is what distinguishes the two.
            return std::signbit(x) ? std::copysign(kPi, y) : std::copysign(0.0, y);
        }
        return std::copysign(kPiOver2, y); // straight up or straight down
    }
    // Magnitude first, quadrant afterwards: the kernel only ever sees a
    // non-negative argument, so the sign handling is a single copysign and
    // signed zeros survive (y = -0 with x > 0 gives -0).
    const double magnitude = atan_nonnegative(std::fabs(y / x));
    if (x > 0.0) {
        return std::copysign(magnitude, y);
    }
    return std::copysign(kPi - magnitude, y);
}

} // namespace scena::runtime
