// SPDX-License-Identifier: Apache-2.0
#include "scena/runtime/detmath.h"

#include <cmath>
#include <limits>

// Deterministic sin/cos via Cody & Waite argument reduction followed by
// fully-parenthesized Taylor kernels on [-pi/4, pi/4]. Reference for the
// reduction technique: W. J. Cody and W. Waite, "Software Manual for the
// Elementary Functions" (Prentice-Hall, 1980). The Taylor coefficients are
// exact rationals (not a Remez fit), so this file is clean-room by
// construction and reproducible from scripts/gen_detmath_coeffs.py.
//
// Only std functions that are IEEE-exact across platforms are used here
// (std::floor, std::fabs); no libm transcendental appears. This is the single
// file the detmath guard (scripts/check_detmath.sh) exempts.

namespace scena::runtime {

namespace {

// generated by scripts/gen_detmath_coeffs.py
// Cody & Waite argument reduction: 2/pi, and pi/2 split into three
// 30-bit chunks so kd*chunk is exact for |kd| < 2^22 (|x| <= 1e6).
inline constexpr double kTwoOverPi = 0x1.45f306dc9c883p-1; // 2/pi
inline constexpr double kPi2Hi = 0x1.921fb54400000p+0;
inline constexpr double kPi2Mid = 0x1.0b4611a400000p-34;
inline constexpr double kPi2Low = 0x1.13198a2c00000p-65;

// sin: r + r^3 * horner(r^2), coeffs (-1)^j/(2j+1)! for j = 1..8.
inline constexpr double kS1 = -0x1.5555555555555p-3;  // (-1)^1/3!
inline constexpr double kS2 = 0x1.1111111111111p-7;   // (-1)^2/5!
inline constexpr double kS3 = -0x1.a01a01a01a01ap-13; // (-1)^3/7!
inline constexpr double kS4 = 0x1.71de3a556c734p-19;  // (-1)^4/9!
inline constexpr double kS5 = -0x1.ae64567f544e4p-26; // (-1)^5/11!
inline constexpr double kS6 = 0x1.6124613a86d09p-33;  // (-1)^6/13!
inline constexpr double kS7 = -0x1.ae7f3e733b81fp-41; // (-1)^7/15!
inline constexpr double kS8 = 0x1.952c77030ad4ap-49;  // (-1)^8/17!

// cos: (1 - r^2/2) + r^4 * horner(r^2), coeffs (-1)^j/(2j)! for j = 2..8.
inline constexpr double kC1 = 0x1.5555555555555p-5;   // (-1)^2/4!
inline constexpr double kC2 = -0x1.6c16c16c16c17p-10; // (-1)^3/6!
inline constexpr double kC3 = 0x1.a01a01a01a01ap-16;  // (-1)^4/8!
inline constexpr double kC4 = -0x1.27e4fb7789f5cp-22; // (-1)^5/10!
inline constexpr double kC5 = 0x1.1eed8eff8d898p-29;  // (-1)^6/12!
inline constexpr double kC6 = -0x1.93974a8c07c9dp-37; // (-1)^7/14!
inline constexpr double kC7 = 0x1.ae7f3e733b81fp-45;  // (-1)^8/16!

// Sine on the reduced argument r in [-pi/4, pi/4], Horner in r^2.
double sin_kernel(double r) noexcept {
    const double r2 = r * r;
    const double r3 = r2 * r;
    double ps = kS8;
    ps = kS7 + r2 * ps;
    ps = kS6 + r2 * ps;
    ps = kS5 + r2 * ps;
    ps = kS4 + r2 * ps;
    ps = kS3 + r2 * ps;
    ps = kS2 + r2 * ps;
    ps = kS1 + r2 * ps;
    return r + r3 * ps;
}

// Cosine on the reduced argument r in [-pi/4, pi/4], Horner in r^2.
double cos_kernel(double r) noexcept {
    const double r2 = r * r;
    const double r4 = r2 * r2;
    double pc = kC7;
    pc = kC6 + r2 * pc;
    pc = kC5 + r2 * pc;
    pc = kC4 + r2 * pc;
    pc = kC3 + r2 * pc;
    pc = kC2 + r2 * pc;
    pc = kC1 + r2 * pc;
    return (1.0 - 0.5 * r2) + r4 * pc;
}

} // namespace

SinCos det_sincos(double x) noexcept {
    // Preserve signed zero: sin(+/-0) = +/-0, cos(+/-0) = 1. Returning x keeps
    // the sign bit; the == comparison treats +0.0 and -0.0 as equal.
    if (x == 0.0) {
        return {x, 1.0};
    }
    // Negated comparison so NaN (all comparisons false) and +/-inf fall out of
    // the accepted domain along with plain over-range magnitudes.
    if (!(std::fabs(x) <= kDetTrigMaxAbsInput)) {
        const double qnan = std::numeric_limits<double>::quiet_NaN();
        return {qnan, qnan};
    }

    // Cody & Waite: reduce x to r in [-pi/4, pi/4] and a quadrant index n.
    // kd is the nearest integer multiple of pi/2; subtracting the 30-bit split
    // one chunk at a time keeps each product kd*chunk exact.
    const double kd = std::floor(x * kTwoOverPi + 0.5);
    const double r = ((x - kd * kPi2Hi) - kd * kPi2Mid) - kd * kPi2Low;
    const int n = static_cast<int>(static_cast<long long>(kd) & 3);

    const double s = sin_kernel(r);
    const double c = cos_kernel(r);
    switch (n) {
    case 0:
        return {s, c};
    case 1:
        return {c, -s};
    case 2:
        return {-s, -c};
    default: // n == 3
        return {-c, s};
    }
}

double det_sin(double x) noexcept {
    // x == -0.0 short-circuits through det_sincos, which returns x, so the
    // -0.0 -> -0.0 guarantee holds without special-casing here.
    return det_sincos(x).sin;
}

double det_cos(double x) noexcept {
    return det_sincos(x).cos;
}

} // namespace scena::runtime
