#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Robomous
# SPDX-License-Identifier: Apache-2.0
"""Generate the constexpr coefficient block for core/src/runtime/detmath.cpp.

Emits ready-to-paste ``constexpr double`` hex-float literals so the vendored
sin/cos implementation has exact, human-auditable constants:

  * the Cody & Waite argument-reduction constants: 2/pi and pi/2 split into
    three 30-bit chunks whose products with the reduction multiple |kd| are
    exact in double precision;
  * the Taylor-series kernel coefficients (-1)^j/(2j+1)! for sin and
    (-1)^j/(2j)! for cos, which are exact rationals — no Remez fitting, so
    the values are trivially clean-room and reproducible from this script;
  * the atan reduction constants (pi/2, pi/6, sqrt(3), tan(pi/12)) and the
    Taylor coefficients (-1)^j/(2j+1) of the atan kernel.

Standard library only (fractions, decimal, math.factorial, struct). Run once
and paste the output into detmath.cpp; the constants never change.
"""

from decimal import Decimal, getcontext
from fractions import Fraction
from math import factorial
import struct

getcontext().prec = 80

# pi to 60+ significant digits (mathematical table constant, not derived from
# any platform's libm). Source: standard math tables.
PI_STR = "3.14159265358979323846264338327950288419716939937510582097494459"
PI = Decimal(PI_STR)


def hex_of(x: float) -> str:
    """Round-trippable hex-float literal for a double."""
    return x.hex()


def double(x) -> float:
    """Nearest double to a Decimal/Fraction/float."""
    return float(x)


def split_30bit(value: Decimal):
    """Split a positive Decimal into hi/mid/low doubles, each holding 30
    significant mantissa bits, so hi+mid+low reconstructs the value to full
    double precision and each chunk multiplies exactly by integers < 2^22."""
    chunks = []
    remainder = value
    for _ in range(3):
        d = double(remainder)
        # Zero the low 22 bits of the 52-bit mantissa -> 30 significant bits.
        bits = struct.unpack("<Q", struct.pack("<d", d))[0]
        bits &= ~((1 << 22) - 1)
        chunk = struct.unpack("<d", struct.pack("<Q", bits))[0]
        chunks.append(chunk)
        remainder = remainder - Decimal(chunk)
    return chunks


def main() -> None:
    two_over_pi = double(Decimal(2) / PI)
    hi, mid, low = split_30bit(PI / 2)

    print("// generated by scripts/gen_detmath_coeffs.py")
    print("// Cody & Waite argument reduction: 2/pi, and pi/2 split into three")
    print("// 30-bit chunks so kd*chunk is exact for |kd| < 2^22 (|x| <= 1e6).")
    print(f"inline constexpr double kTwoOverPi = {hex_of(two_over_pi)}; // 2/pi")
    print(f"inline constexpr double kPi2Hi = {hex_of(hi)};")
    print(f"inline constexpr double kPi2Mid = {hex_of(mid)};")
    print(f"inline constexpr double kPi2Low = {hex_of(low)};")
    print()
    # Verify the split reconstructs pi/2.
    assert hi + mid + low == double(PI / 2), "pi/2 split lost precision"

    # sin kernel: r + r^3 * (kS1 + kS2 r^2 + ... ), coefficients (-1)^j/(2j+1)!
    # for j = 1..8 -> terms r^3 .. r^17.
    print("// sin: r + r^3 * horner(r^2), coeffs (-1)^j/(2j+1)! for j = 1..8.")
    for idx, j in enumerate(range(1, 9), start=1):
        c = Fraction((-1) ** j, factorial(2 * j + 1))
        print(f"inline constexpr double kS{idx} = {hex_of(double(c))}; "
              f"// (-1)^{j}/{2 * j + 1}!")
    print()
    # cos kernel: (1 - 0.5 r^2) + r^4 * (kC1 + kC2 r^2 + ...),
    # coefficients (-1)^j/(2j)! for j = 2..8 -> terms r^4 .. r^16.
    print("// cos: (1 - r^2/2) + r^4 * horner(r^2), coeffs (-1)^j/(2j)! for j = 2..8.")
    for idx, j in enumerate(range(2, 9), start=1):
        c = Fraction((-1) ** j, factorial(2 * j))
        print(f"inline constexpr double kC{idx} = {hex_of(double(c))}; "
              f"// (-1)^{j}/{2 * j}!")
    print()

    # atan reduction: fold [0, inf[ to [0, tan(pi/12)] with
    #   atan(t) = pi/2 - atan(1/t)                    for t > 1
    #   atan(t) = pi/6 + atan((t*sqrt3 - 1)/(t + sqrt3))  for t > tan(pi/12)
    # sqrt(3) and tan(pi/12) = 2 - sqrt(3) come from the same exact radical.
    sqrt3 = Decimal(3).sqrt()
    print("// atan argument reduction: pi/2, pi/6, sqrt(3) and the fold")
    print("// threshold tan(pi/12) = 2 - sqrt(3).")
    print(f"inline constexpr double kPi = {hex_of(double(PI))};")
    print(f"inline constexpr double kPiOver2 = {hex_of(double(PI / 2))};")
    print(f"inline constexpr double kPiOver6 = {hex_of(double(PI / 6))};")
    print(f"inline constexpr double kSqrt3 = {hex_of(double(sqrt3))};")
    print(f"inline constexpr double kTanPiOver12 = {hex_of(double(2 - sqrt3))};")
    print()
    # atan kernel: u + u^3 * (kA1 + kA2 u^2 + ...), coefficients
    # (-1)^j/(2j+1) for j = 1..15 -> terms u^3 .. u^31. On |u| <= tan(pi/12)
    # the first neglected term is below 1e-20 relative.
    print("// atan: u + u^3 * horner(u^2), coeffs (-1)^j/(2j+1) for j = 1..15.")
    for idx, j in enumerate(range(1, 16), start=1):
        c = Fraction((-1) ** j, 2 * j + 1)
        print(f"inline constexpr double kA{idx} = {hex_of(double(c))}; "
              f"// (-1)^{j}/{2 * j + 1}")


if __name__ == "__main__":
    main()
